services:
  backend:
    build: ./services/backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file: .env.prod

  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    env_file: .env.prod

